feat: modularize shell configuration and integrate Starship, eza, and delta tools

diff --git a/config/bashrc b/config/bashrc
--- a/config/bashrc
+++ b/config/bashrc
@@ -1,6 +1,7 @@
-# ~/.bashrc: executed by bash(1) for non-login shells.
-# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
-# for examples
+##############################################################################
+# ~/.bashrc — Bash Configuration
+# Managed by dotfiles: github.com/nyambogahezron/dotfiles
+##############################################################################
 
 # If not running interactively, don't do anything
 case $- in
@@ -8,110 +9,247 @@ case $- in
       *) return;;
 esac
 
-# don't put duplicate lines or lines starting with space in the history.
-# See bash(1) for more options
+#  XDG Base Directories ─
+
+export XDG_DATA_HOME="$HOME/.local/share"
+export XDG_CONFIG_HOME="$HOME/.config"
+export XDG_STATE_HOME="$HOME/.local/state"
+export XDG_CACHE_HOME="$HOME/.cache"
+
+#  PATH ──
+
+export PATH="$HOME/.local/bin:$PATH"
+export GOPATH="$HOME/go"
+export GOROOT="/usr/local/go"
+export PATH="$GOPATH/bin:$GOROOT/bin:$PATH"
+export PATH="$HOME/.cargo/bin:$PATH"
+export PATH="$HOME/.config/composer/vendor/bin:$PATH"
+
+#  Editor 
+
+export EDITOR="nvim"
+export VISUAL="nvim"
+export PAGER="less"
+
+#  NVM (Node Version Manager) ─
+
+export NVM_DIR="$HOME/.nvm"
+[ -s "$NVM_DIR/nvm.sh" ]          && \. "$NVM_DIR/nvm.sh"
+[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
+
+#  History ──
+
 HISTCONTROL=ignoreboth
-
-# append to the history file, don't overwrite it
+HISTSIZE=50000
+HISTFILESIZE=100000
 shopt -s histappend
-
-# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
-HISTSIZE=1000
-HISTFILESIZE=2000
-
-# check the window size after each command and, if necessary,
-# update the values of LINES and COLUMNS.
 shopt -s checkwinsize
+shopt -s globstar 2>/dev/null
 
-# If set, the pattern "**" used in a pathname expansion context will
-# match all files and zero or more directories and subdirectories.
-#shopt -s globstar
+#  Color Support ──
 
-# make less more friendly for non-text input files, see lesspipe(1)
-[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
-
-# set variable identifying the chroot you work in (used in the prompt below)
-if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
-    debian_chroot=$(cat /etc/debian_chroot)
+if [ -x /usr/bin/dircolors ]; then
+    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
 fi
 
-# set a fancy prompt (non-color, unless we know we "want" color)
-case "$TERM" in
-    xterm-color|*-256color) color_prompt=yes;;
-esac
+# make less more friendly for non-text input files
+[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
 
-# uncomment for a colored prompt, if the terminal has the capability; turned
-# off by default to not distract the user: the focus in a terminal window
-# should be on the output of commands, not on the prompt
-#force_color_prompt=yes
+#  Navigation Aliases 
 
-if [ -n "$force_color_prompt" ]; then
-    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
-	# We have color support; assume it's compliant with Ecma-48
-	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
-	# a case would tend to support setf rather than setaf.)
-	color_prompt=yes
+alias ..='cd ..'
+alias ...='cd ../..'
+alias ....='cd ../../..'
+alias ~='cd ~'
+
+#  ls / eza ─
+
+if command -v eza &>/dev/null; then
+    alias ls='eza --color=always --group-directories-first --icons'
+    alias ll='eza -alF --color=always --group-directories-first --icons --git'
+    alias la='eza -a --color=always --group-directories-first --icons'
+    alias l='eza -F --color=always --group-directories-first --icons'
+    alias lt='eza -aT --color=always --group-directories-first --icons --level=2'
+else
+    alias ls='ls --color=auto'
+    alias ll='ls -alF'
+    alias la='ls -A'
+    alias l='ls -CF'
+    alias lt='ls -ltrh'
+fi
+
+#  bat (better cat) ──
+
+if command -v bat &>/dev/null; then
+    alias cat='bat --style=plain'
+elif command -v batcat &>/dev/null; then
+    alias cat='batcat --style=plain'
+fi
+
+#  System Aliases ─
+
+alias grep='grep --color=auto'
+alias fgrep='fgrep --color=auto'
+alias egrep='egrep --color=auto'
+alias rm='rm -i'
+alias cp='cp -i'
+alias mv='mv -i'
+alias mkdir='mkdir -p'
+alias cls='clear'
+alias c='clear'
+alias h='history'
+alias j='jobs -l'
+alias path='echo -e ${PATH//:/\\n}'
+alias now='date +"%T"'
+alias nowdate='date +"%d-%m-%Y"'
+alias rmd='rm -rf'
+alias ping='ping -c 10'
+alias less='less -R'
+alias mountedinfo='df -hT'
+alias ps='ps auxf'
+alias p="ps aux | grep "
+alias f="find . | grep "
+alias hgrep="history | grep "
+alias mx='chmod a+x'
+alias 755='chmod -R 755'
+alias 644='chmod -R 644'
+alias myip='curl -s ifconfig.me && echo'
+command -v btop &>/dev/null && alias top='btop'
+command -v dust &>/dev/null && alias du='dust'
+
+# System update
+alias update='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt autoclean -y \
+  ; sudo snap refresh 2>/dev/null ; flatpak update -y 2>/dev/null'
+alias install='sudo apt install'
+alias remove='sudo apt remove'
+alias search='apt search'
+
+# Alert for long running commands
+alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
+
+#  Git Aliases ─
+
+alias g='git'
+alias gs='git status -sb'
+alias ga='git add'
+alias gc='git commit'
+alias gp='git push'
+alias gpf='git push --force-with-lease'
+alias gl='git log --oneline --graph --decorate --all'
+alias gd='git diff'
+alias gb='git branch'
+alias gco='git checkout'
+alias gcb='git checkout -b'
+alias gcom='git add . && git commit -m'
+alias gpl='git pull'
+alias gst='git stash'
+alias gstp='git stash pop'
+alias lazyg='git add . && git commit -m "$1" && git push'
+command -v lazygit &>/dev/null && alias lg='lazygit'
+
+#  Docker Aliases ─
+
+alias d='docker'
+alias dc='docker compose'
+alias dps='docker ps'
+alias dpsa='docker ps -a'
+alias di='docker images'
+alias dex='docker exec -it'
+alias dlog='docker logs -f'
+alias docker-clean='docker container prune -f && docker image prune -f && docker network prune -f && docker volume prune -f'
+alias dcu='docker compose up -d'
+alias dcd='docker compose down'
+
+#  Dev Aliases ─
+
+alias nv='nvim'
+alias vim='nvim'
+alias v='nvim .'
+alias py='python3'
+alias dotfiles='cd ~/Projects/dotfiles'
+alias edotfiles='nvim ~/Projects/dotfiles'
+alias reload='source ~/.bashrc && echo "✓ Bashrc reloaded"'
+
+#  FUNCTIONS 
+
+mkcd() { mkdir -p "$1" && cd "$1"; }
+
+extract() {
+    if [ -f "$1" ]; then
+        case "$1" in
+            *.tar.bz2) tar xjf "$1" ;; *.tar.gz)  tar xzf "$1" ;;
+            *.tar.xz)  tar xJf "$1" ;; *.bz2)     bunzip2 "$1" ;;
+            *.gz)      gunzip "$1"  ;; *.tar)      tar xf "$1"  ;;
+            *.zip)     unzip "$1"   ;; *.7z)       7z x "$1"    ;;
+            *) echo "'$1' cannot be extracted" ;;
+        esac
     else
-	color_prompt=
+        echo "'$1' is not a valid file"
+    fi
+}
+
+backup() { cp "$1"{,.backup-$(date +%Y%m%d-%H%M%S)} && echo "✓ Backed up $1"; }
+
+up() {
+    local d="" limit=${1:-1}
+    for ((i = 1; i <= limit; i++)); do d="$d/.."; done
+    d=$(echo "$d" | sed 's/^\///')
+    [ -z "$d" ] && d=".."
+    cd "$d"
+}
+
+cd() {
+    if [ -n "$1" ]; then builtin cd "$@" && ls
+    else builtin cd ~ && ls; fi
+}
+
+ftext() { grep -iIHrn --color=always "$1" . | less -r; }
+psgrep() { ps aux | grep -v grep | grep -i -e VSZ -e "$1"; }
+gclone() { git clone "$1" && cd "$(basename "$1" .git)"; }
+mkproject() { mkcd "$1" && git init && echo "# $1" > README.md && echo "✓ Project '$1' ready"; }
+
+killport() {
+    local pid; pid=$(lsof -t -i:"$1")
+    if [ -n "$pid" ]; then kill -9 "$pid" && echo "✓ Killed PID $pid on port $1"
+    else echo "No process on port $1"; fi
+}
+
+#  FZF 
+
+export FZF_DEFAULT_OPTS="
+    --height=60% --layout=reverse --border=rounded
+    --prompt='❯ ' --pointer='▶' --marker='✓'
+    --color=fg:#cdd6f4,bg:#1e1e2e,hl:#f38ba8
+    --color=fg+:#cdd6f4,bg+:#313244,hl+:#f38ba8
+    --color=info:#cba6f7,prompt:#cba6f7,pointer:#f5c2e7
+    --color=marker:#a6e3a1,spinner:#f5c2e7,header:#f38ba8
+"
+
+if command -v fd &>/dev/null; then
+    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
+fi
+
+[ -f ~/.fzf.bash ] && source ~/.fzf.bash
+[ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash
+
+#  Zoxide 
+
+if command -v zoxide &>/dev/null; then
+    eval "$(zoxide init bash --cmd z)"
+fi
+
+#  Programmable Completion ─
+
+if ! shopt -oq posix; then
+    if [ -f /usr/share/bash-completion/bash_completion ]; then
+        . /usr/share/bash-completion/bash_completion
+    elif [ -f /etc/bash_completion ]; then
+        . /etc/bash_completion
     fi
 fi
 
-if [ "$color_prompt" = yes ]; then
-    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
-else
-    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
-fi
-unset color_prompt force_color_prompt
+#  Starship Prompt 
 
-# If this is an xterm set the title to user@host:dir
-case "$TERM" in
-xterm*|rxvt*)
-    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
-    ;;
-*)
-    ;;
-esac
-
-# enable color support of ls and also add handy aliases
-if [ -x /usr/bin/dircolors ]; then
-    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
-    alias ls='ls --color=auto'
-    #alias dir='dir --color=auto'
-    #alias vdir='vdir --color=auto'
-
-    alias grep='grep --color=auto'
-    alias fgrep='fgrep --color=auto'
-    alias egrep='egrep --color=auto'
-fi
-
-# colored GCC warnings and errors
-#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
-
-# some more ls aliases
-alias ll='ls -alF'
-alias la='ls -A'
-alias l='ls -CF'
-
-# Add an "alert" alias for long running commands.  Use like so:
-#   sleep 10; alert
-alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
-
-# Alias definitions.
-# You may want to put all your additions into a separate file like
-# ~/.bash_aliases, instead of adding them here directly.
-# See /usr/share/doc/bash-doc/examples in the bash-doc package.
-
-if [ -f ~/.bash_aliases ]; then
-    . ~/.bash_aliases
-fi
-
-# enable programmable completion features (you don't need to enable
-# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
-# sources /etc/bash.bashrc).
-if ! shopt -oq posix; then
-  if [ -f /usr/share/bash-completion/bash_completion ]; then
-    . /usr/share/bash-completion/bash_completion
-  elif [ -f /etc/bash_completion ]; then
-    . /etc/bash_completion
-  fi
+if command -v starship &>/dev/null; then
+    eval "$(starship init bash)"
 fi
